//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weather.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///&lt;svg
        ///   xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///   xmlns:cc=&quot;http://creativecommons.org/ns#&quot;
        ///   xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
        ///   xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;
        ///   xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///   xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string weather_clear {
            get {
                return ResourceManager.GetString("weather_clear", resourceCulture);
            }
        }
        
        internal static byte[] weather_clear_night {
            get {
                object obj = ResourceManager.GetObject("weather_clear_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] weather_few_clouds {
            get {
                object obj = ResourceManager.GetObject("weather_few_clouds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] weather_few_clouds_night {
            get {
                object obj = ResourceManager.GetObject("weather_few_clouds_night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] weather_overcast {
            get {
                object obj = ResourceManager.GetObject("weather_overcast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] weather_severe_alert {
            get {
                object obj = ResourceManager.GetObject("weather_severe_alert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] weather_showers {
            get {
                object obj = ResourceManager.GetObject("weather_showers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] weather_showers_scattered {
            get {
                object obj = ResourceManager.GetObject("weather_showers_scattered", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] weather_snow {
            get {
                object obj = ResourceManager.GetObject("weather_snow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] weather_storm {
            get {
                object obj = ResourceManager.GetObject("weather_storm", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
